import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
[window]
padding.x = 5
padding.y = 5
opacity = 0.9

[font]

normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
size = 18.0





